oc_fentis_login:
    path:     /
    defaults: { _controller: OCFentisBundle:Fentis:first }

oc_fentis_index:
    path:     /index
    defaults: { _controller: OCFentisBundle:Fentis:index }
    
oc_fentis_chat:
    path:     /chat
    defaults: { _controller: OCFentisBundle:Fentis:chat }
    
oc_fentis_form:
    path:     /form
    defaults: { _controller: OCFentisBundle:Fentis:form }
    
oc_fentis_ajout:
    path:     /ajout
    defaults: { _controller: OCFentisBundle:Fentis:ajout }
    
oc_fentis_voir:
    path:     /voir
    defaults: { _controller: OCFentisBundle:Fentis:voir }

oc_fentis_modif:
    path:     /modif
    defaults: { _controller: OCFentisBundle:Fentis:modif }
    
oc_fentis_promote:
    path:     /promotestart
    defaults: { _controller: OCFentisBundle:Fentis:promotestart }
    
oc_fentis_levelup:
    path:     /levelup/{user}
    defaults: { _controller: OCFentisBundle:Fentis:levelup}