<?php

namespace OC\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function myDeleteUser($user){
        $um = $this
                ->get('fos_user.user_manager');
        
        $um->deleteUser($user);
        
        return $this->redirect($this->generateUrl('oc_fentis_welcome', array(
                'name' => 'bleubleubleu'
            )));
    }
}
