<?php

namespace OC\FentisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FichePersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichePersoRepository extends EntityRepository
{
}
