<?php

namespace OC\FentisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * equipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipRepository extends EntityRepository
{
}
