<?php

namespace OC\FentisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
        public function myFindAll(){
        return $this
                ->createQueryBuilder('a')
                ->getQuery()
                ->getResult()
                ;
    }
}
